# Generated by Django 4.1.7 on 2023-03-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('country_of_origin', models.CharField(max_length=25)),
                ('retail_revenue', models.FloatField(null=True)),
                ('parent_company_revenue', models.FloatField(null=True)),
                ('parent_company_net_income', models.FloatField(null=True)),
                ('dominant_operational_format', models.CharField(max_length=256, null=True)),
                ('countries_of_operation', models.IntegerField(null=True)),
                ('retail_revenue_cagr', models.FloatField(null=True)),
            ],
        ),
    ]
