# Generated by Django 4.1.7 on 2023-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailers',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
