# Generated by Django 4.1.7 on 2023-03-14 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('contactnumber', models.CharField(max_length=56)),
                ('streetaddress1', models.CharField(max_length=256)),
                ('streetaddress2', models.CharField(max_length=256, null=True)),
                ('suburb', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('grossincome', models.IntegerField(max_length=24)),
                ('expenses', models.IntegerField(max_length=24)),
                ('bankaccounttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.bankaccounttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bank Account Applications',
            },
        ),
    ]
