# Generated by Django 4.1.7 on 2023-03-14 20:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0003_bankaccountapplicationstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='expenses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='grossincome',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.bankaccountapplicationstatus'),
        ),
    ]
