# Generated by Django 4.1.7 on 2023-03-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0004_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='bankaccounttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.bankaccounttype', verbose_name='Bank account type'),
        ),
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='contactnumber',
            field=models.CharField(max_length=56, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='country',
            field=models.CharField(default=1, max_length=256, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='expenses',
            field=models.IntegerField(verbose_name='Total monthly expenses'),
        ),
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='grossincome',
            field=models.IntegerField(verbose_name='Gross monthly income'),
        ),
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='province',
            field=models.CharField(default=1, max_length=256, verbose_name='Provice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='streetaddress1',
            field=models.CharField(default=1, max_length=256, verbose_name='Street address 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='streetaddress2',
            field=models.CharField(max_length=256, null=True, verbose_name='Street address 2'),
        ),
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='suburb',
            field=models.CharField(default=1, max_length=256, verbose_name='Suburb'),
            preserve_default=False,
        ),
    ]
