# Generated by Django 4.1.7 on 2023-03-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0005_alter_bankaccountapplications_bankaccounttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='province',
            field=models.CharField(max_length=256, verbose_name='Province'),
        ),
    ]
