# Generated by Django 4.1.7 on 2023-04-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0007_rename_datetime_bankaccount_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bankaccountapplications',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
