# Generated by Django 4.1.7 on 2023-04-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0008_alter_bankaccount_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounttype',
            name='description',
            field=models.CharField(default=1, max_length=300, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccounttype',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
