# Generated by Django 4.1.7 on 2023-04-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_birthdate_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='income_level',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
