# Generated by Django 4.1.7 on 2023-04-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_income_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='income_level',
        ),
    ]
