# Generated by Django 4.1.7 on 2023-04-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_income_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=56)),
                ('lower', models.IntegerField()),
                ('upper', models.IntegerField()),
            ],
        ),
    ]
