# Generated by Django 4.1.7 on 2023-03-15 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankaccounts', '0006_alter_bankaccountapplications_province'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_account', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_account', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.bankaccount')),
            ],
        ),
    ]
