# Generated by Django 4.1.7 on 2023-03-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransactions',
            name='source_bank',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debittransactions',
            name='destination_bank',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
