# Generated by Django 4.1.7 on 2023-03-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_credittransactions_source_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debittransactions',
            name='user',
        ),
    ]
