# Generated by Django 4.1.7 on 2023-03-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_credittransactions_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debittransactions',
            name='recipient_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='debittransactions',
            name='destination_bank',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
