# Generated by Django 4.1.7 on 2023-03-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_debittransactions_recipient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransactions',
            name='from_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='credittransactions',
            name='source_bank',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
