# Generated by Django 4.1.7 on 2023-03-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_credittransactions_from_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransactions',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='debittransactions',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
