# Generated by Django 4.1.7 on 2023-03-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_credittransactions_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
            ],
        ),
        migrations.CreateModel(
            name='DebitTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
            ],
        ),
    ]
