# Generated by Django 4.1.7 on 2023-03-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='contentitem',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_log_message',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
