# Generated by Django 4.1.7 on 2023-04-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_remove_activity_contentitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
            ],
            options={
                'verbose_name_plural': 'Activity types',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
