# Generated by Django 4.1.7 on 2023-04-05 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activitytype_activity_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activitytype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activity.activitytype'),
            preserve_default=False,
        ),
    ]
