# Generated by Django 4.1.7 on 2023-04-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_activity_activitytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
