# Generated by Django 4.1.7 on 2023-04-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_rename_datetime_activity_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activitytype',
        ),
    ]
