# Generated by Django 3.1.2 on 2020-10-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentseries',
            options={'verbose_name_plural': 'Content series'},
        ),
        migrations.AddField(
            model_name='contentitem',
            name='series',
            field=models.ManyToManyField(to='content.ContentSeries'),
        ),
    ]
